### ISSUE TITLE
铁电实验数据处理

### ISSUE THREAD

**Issue by Wonder0225** [njudii/ModPhysExperiment#1]
利用Python封装了一个类，提供电滞回线基本的数据处理功能：[DataAnalysis.txt](https://github.com/njudii/ModPhysExperiment/files/14965887/DataAnalysis.txt)

**Comment by github-young** [comment]
Thank you. Please file a PR and merge the code into this repo. If you are interested in contributing more to this repo, I can invite you as a collaborator of this repo.

**Comment by Wonder0225** [comment]
I didn't clone the repository so I upload the code through issue. I would be happy if I can be a collaborator of this repo, then I can upload my ploting code after finishing the course this term.
